return {
    -- show document symbols in right window
    "simrat39/symbols-outline.nvim",
    lazy = true,
    cmd = "SymbolsOutline",
    opts = {
        highlight_hovered_item = true,
        show_guides = true,
        auto_preview = false,
        position = "right",
        relative_width = true,
        width = 25,
        auto_close = false,
        show_numbers = false,
        show_relative_numbers = false,
        show_symbol_details = true,
        preview_bg_highlight = "Pmenu",
        autofold_depth = nil,
        auto_unfold_hover = true,
        fold_markers = {"", ""},
        wrap = false,
        keymaps = { -- these keymaps can be a string or a table for multiple keys
            close = {"<Esc>", "q"},
            goto_location = "<Cr>",
            focus_location = "o",
            hover_symbol = "<C-\\>",
            toggle_preview = "K",
            rename_symbol = "r",
            code_actions = "a",
            fold = "h",
            unfold = "l",
            fold_all = "W",
            unfold_all = "E",
            fold_reset = "R"
        },
        lsp_blacklist = {},
        symbol_blacklist = {},
        symbols = {
            Array = { icon = "", hl = "@constant" },
            Boolean = { icon = "", hl = "@boolean" },
            Class = { icon = "", hl = "@type" },
            Component = { icon = "", hl = "@function" },
            Constant = { icon = "", hl = "@constant" },
            Constructor = { icon = "", hl = "@constructor" },
            Enum = { icon = "", hl = "@type" },
            EnumMember = { icon = "", hl = "@field" },
            Event = { icon = "🗲", hl = "@type" },
            Field = { icon = "", hl = "@field" },
            File = { icon = "", hl = "@text.url" },
            Fragment = { icon = "", hl = "@constant" },
            Function = { icon = "", hl = "@function" },
            Interface = { icon = "", hl = "@type" },
            Key = { icon = "🔐", hl = "@type" },
            Method = { icon = "ƒ", hl = "@method" },
            Module = { icon = "", hl = "@namespace" },
            Namespace = { icon = "", hl = "@namespace" },
            Null = { icon = "󰟢", hl = "@type" },
            Number = { icon = "", hl = "@number" },
            Object = { icon = "", hl = "@type" },
            Operator = { icon = "", hl = "@operator" },
            Package = { icon = "", hl = "@namespace" },
            Property = { icon = "", hl = "@method" },
            String = { icon = "", hl = "@string" },
            Struct = { icon = "", hl = "@type" },
            TypeParameter = { icon = "", hl = "@parameter" },
            Variable = { icon = "", hl = "@constant" },
        }
    }
}
