" set vim shell. NOTE: pwsh has issues with `:PlugClean`
set shell=pwsh.exe
set shellcmdflag=\ -ExecutionPolicy\ RemoteSigned\ -NoProfile\ -Nologo\ -NonInteractive\ -Command

" cursor types
" 0 = blinking block
" 1 = blinking block (default)
" 2 = steady block
" 3 = blinking underline
" 4 = steady underline
" 5 = blinking bar (xterm)
" 6 = steady bar (xterm)

" set cursor type on vim startup
autocmd VimEnter * silent exec "! echo -ne '\e[1 q'" 
" set cursor type on vim exit
autocmd VimLeave * silent exec "! echo -ne '\e[3 q'" 

" cursor for everything else
let &t_EI = "\e[1 q" 
" cursor for insert mode
let &t_SI = "\e[3 q" 

" automatic installation of vim-plug and missing plugins
if empty(glob('$HOME/vimfiles/autoload/plug.vim'))
  silent !curl -fLo $HOME/vimfiles/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
      \| PlugInstall --sync | source $MYVIMRC
      \| endif

" will need to change the folder location below if using something else
" Linux default = ~/.vim/plugged; Windows default = $HOME/vimfiles/plugged
call plug#begin('$HOME/vimfiles/plugged')

"Plug 'ludovicchabant/vim-gutentags' " generate tags
"Plug 'mhinz/vim-signify' " adds VCS status
"Plug 'rafi/awesome-vim-colorschemes' " a collection of color schemes - has onehalf and more
"Plug 'plasticboy/vim-markdown' " syntax highlighting, matching rules and mapping for Markdown
Plug 'ackyshake/VimCompletesMe' " tab completion
Plug 'chun-yang/auto-pairs' " inserts/deletes brackets, parens, and quotes in pairs
Plug 'ConradIrwin/vim-bracketed-paste' " allows you to paste text from other apps without indent
Plug 'bkad/CamelCaseMotion' " move between camel case words - use <Leader><action>
Plug 'dkarter/bullets.vim' " automate bullet lists and numbering
Plug 'easymotion/vim-easymotion' " easier way to move around vim - use <Leader><Leader><action>
Plug 'frazrepo/vim-rainbow' " adds color to brackets and parenthesis
Plug 'iggredible/totitle-vim' " title case text - use 'gt'
Plug 'inkarkat/vim-SpellCheck' " adds a better spell checker
Plug 'inkarkat/vim-ingo-library' " dependency for vim-spellcheck
Plug 'inkarkat/vim-visualrepeat' " like vim-repeat but for VISUAL mode
Plug 'junegunn/fzf.vim' " command-line fuzzy finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " needed for above
Plug 'junegunn/vim-peekaboo' " see contents of registries with '@' or double quotes
Plug 'justinmk/vim-sneak' " jump to any located specified by two characters - use 's<char><char>
Plug 'michaeljsmith/vim-indent-object' " adds auto indent for objects
Plug 'mg979/vim-visual-multi' " adds multiple cursors
"Plug 'neoclide/coc.nvim', {'branch': 'release'} " auto completion for code
Plug 'preservim/nerdtree' " file explorer for vim - use ':NERDTree' >> set alias for F6
Plug 'preservim/vim-markdown' " syntax highlighting, matching rule and mapping
"Plug 'psliwka/vim-dirtytalk, { 'do': 'DirtytalkUpdate' } " spellcheck dictionary for programmers
Plug 'ryanoasis/vim-devicons' " adds icons to vim
Plug 'sheerun/vim-polyglot' " syntax highlighting for various languages
Plug 'simnalamburt/vim-mundo' " visualize the vim undo tree >> set alias for F5
Plug 'sonph/onehalf', { 'rtp': 'vim' } " color scheme for vim layout
Plug 'terryma/vim-smooth-scroll' " smooth scrolling
Plug 'tpope/vim-commentary' " comments stuff out - use 'gcc' or 'gc' in visual mode
Plug 'tpope/vim-fugitive' " git commands - call with :Git
Plug 'tpope/vim-repeat' " repeat last `.` command as a whole
Plug 'tpope/vim-surround' " surround text - use cs, ds, ys
Plug 'vim-airline/vim-airline' " better status bar than above
Plug 'vim-airline/vim-airline-themes' " themes for the status bar - use ':AirlineTheme <theme>'
Plug 'vimwiki/vimwiki' " organize notes and ideas

call plug#end()

" call other configurations
source C:/Users/Laz/vimfiles/settings/settings.vim
source C:/Users/Laz/vimfiles/settings/remapings.vim
source C:/Users/Laz/vimfiles/settings/functions.vim
"source C:/Users/Laz/vimfiles/settings/barconfigs.vim
"source C:/Users/Laz/vimfiles/settings/coc-configs.vim
