return {
    kind = {
        Array = "",
        Boolean = "",
        -- Class = "",
        Class = "󰠱", -- 5 character hex code
        Color = "",
        Component = "",
        -- Constant = "",
        Constant = "󰏿", -- 5 character hex code
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "󰜢", -- 5 character hex code
        File = "󰈙", -- 5 character hex code
        Fragment = "",
        Folder = "",
        Function = "ƒ", -- 3 character hex code
        -- Interface = "",
        Interface = "",
        Key = "",
        Keyword = "󰌋", -- 5 character hex code
        Method = "󰆧", -- 5 character hex code
        Module = "",
        Namespace = "",
        Null = "󰟢", -- 5 character hex code
        Number = "",
        Object = "",
        -- Operator = "",
        Operator = "󰆕", -- 5 character hex code
        Package = "",
        Property = "",
        -- Reference = "",
        Reference = "󰈇", -- 5 character hex code
        -- Snippet = "",
        Snippet = "",
        String = "",
        -- Struct = "󰙅", -- 5 character hex code
        Struct = "",
        Text = "󰉿", -- 5 character hex code
        TypeParameter = "",
        -- Unit = "",
        Unit = "󰑭", -- 5 character hex code
        Value = "󰎠", -- 5 character hex code
        -- Variable = "",
        Variable = "󰀫", -- 5 character hex code
    },
    git = {
        Branch = "",
        Copilot = "",
        Diff = "",
        FileDeleted = "",
        FileIgnored = "◌",
        FileRenamed = "",
        FileStaged = "✓",
        FileUnmerged = "",
        FileUnstaged = "✗",
        FileUntracked = "★",
        LineAdded = "",
        LineModified = "",
        LineRemoved = "",
        Octoface = "",
        Repo = "",
    },
    ui = {
        ArrowCircleDown = "",
        ArrowCircleLeft = "",
        ArrowCircleRight = "",
        ArrowCircleUp = "",
        BoldArrowDown = "",
        BoldArrowLeft = "",
        BoldArrowRight = "",
        BoldArrowUp = "",
        BoldClose = "",
        BoldDividerLeft = "",
        BoldDividerRight = "",
        BoldLineDashedMiddle = "┋",
        BoldLineLeft = "▎",
        BoldLineMiddle = "┃",
        BookMark = "",
        BoxChecked = "",
        Bug = "",
        Calendar = "",
        Check = "",
        ChevronShortDown = "",
        ChevronShortLeft = "",
        ChevronShortRight = "",
        ChevronShortUp = "",
        Circle = "",
        Close = "󰅖", -- 5 character hex code
        CloudDownload = "",
        Code = "",
        Comment = "",
        Dashboard = "",
        DebugConsole = "",
        DividerLeft = "",
        DividerRight = "",
        DoubleChevronRight = "»", -- 2 character hex code
        Ellipsis = "",
        EmptyFolder = "",
        EmptyFolderOpen = "",
        File = "",
        FileSymlink = "",
        Files = "",
        FindFile = "󰈞", -- 5 character hex code
        FindText = "󰊄", -- 5 character hex code
        Fire = "",
        Folder = "󰉋", -- 5 character hex code
        FolderOpen = "",
        FolderSymlink = "",
        Forward = "",
        Gear = "",
        History = "",
        Lightbulb = "",
        LineLeft = "▏",
        LineMiddle = "│",
        List = "",
        Lock = "",
        Modified = "●",
        NewFile = "",
        Note = "",
        Package = "", -- duplicate
        Pencil = "󰏫", -- 5 character hex code
        Plus = "",
        Project = "",
        RecentFiles = "",
        Scopes = "",
        Search = "",
        Skull = "💀", -- 5 character hex code
        SignIn = "",
        SignOut = "",
        Stacks = "",
        Tab = "󰌒", -- 5 character hex code
        Table = "",
        Target = "󰀘", -- 5 character hex code
        Telescope = "",
        Text = "",
        Tree = "",
        Triangle = "󰐊", -- 5 character hex code
        TriangleShortArrowDown = "",
        TriangleShortArrowLeft = "",
        TriangleShortArrowRight = "",
        TriangleShortArrowUp = "",
        Watches = "󰂥", -- 5 character hex code
    },
    diagnostics = {
        BoldError = "",
        BoldHint = "", -- duplicate
        BoldInformation = "",
        BoldQuestion = "",
        BoldWarning = "",
        Debug = "",
        Error = "",
        Hint = "",
        Information = "",
        Question = "",
        Trace = "✎",
        Warning = "",
    },
    misc = {
        Answer = "ﮧ",
        BorderLeft = "",
        BorderRight = "",
        Circular = "",
        CircuitBoard = "",
        Clock = "",
        Collapsed = "",
        CurrentLine = "",
        Cursor = "󱄧", -- 5 character hex code
        Dashboard = "󰕮",
        Expand = "",
        Explorer = "",
        FZF = "", -- 4 character hex code
        Harpoon = "󱡀", -- 5 character hex code
        Package = "", -- duplicate
        Pending = "➜",
        Prompt = "",
        Question = "",
        Quickfix = "󱖫", -- 5 character hex code
        Quit = "",
        Robot = "󰚩", -- 5 character hex code
        Settings = "",
        Smiley = "",
        Squirrel = "",
        Tag = "",
        Watch = "",
        UI = "󰙵", -- 5 character hex code
        VENV = "󰂓", -- 5 character hex code
    }
}
